name: Continuous Integration
on: [push, pull_request]
jobs:
  build:
    # Newer images have CONFIG_SND_PCM disabled
    runs-on: ubuntu-16.04
    steps:
    - name: Install prerequisites
      run: sudo apt update && sudo apt install dkms
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install (debug)
      run: sudo ./install.sh
    - name: Uninstall (debug)
      run: sudo ./uninstall.sh
    - name: Install (release)
      run: sudo ./install.sh --release
    - name: Uninstall (release)
      run: sudo ./uninstall.sh
